### ISSUE TITLE
Which DMG file u used 

### ISSUE THREAD

**Issue by rahat14** [yahgoo/Hackintosh-HP-840-G3-Opencore-Monterey#2]
when i try the apple logo appears and restarts the pc. can you share the dmg file with me .

**Comment by yahgoo** [comment]
There is no dmg. Have u disable VT-d in your bios? Show me a video on the boot sequence from start to pc start.

**Comment by rahat14** [comment]
I will be uploading the video later today. in the mean time here is the list what i tried so far. 
-> used Open core method to obtain the recovery file via python script 
link-> https://dortania.github.io/OpenCore-Install-Guide/installer-guide/winblows-install.html#downloading-macos
-> used your efi and  the file i downloaded put on a pen drive with necessary file format. 
-> the file structure look like this  link - https://dortania.github.io/OpenCore-Install-Guide/assets/img/com-efi-done.a6fb730e.png
-> the with this open core works but then apple logo appears  load some time then restarts. 

can you please use your some time to guide me with the full process . i am in a dire need of this.

**Comment by yahgoo** [comment]
I used Mac to do a clean install. For windows, please follow these instructions to create a usb Monterey installer.
https://www.hackintoshshop.com/3262/hackintosh-monterey-guide/

Then copy my EFI to the usb and install Monterey.
U should see a verbose boot log while booting. 
Give it a shot!

**Comment by yahgoo** [comment]
1. Set bios settings as follows:
Advanced tab:
Boot options:
- Fast Boot = Disabled
- Network (PXE) Boot = Disabled
Secure Boot Configuration:
- "Legacy Support Enable and Secure Boot Disable"
System Options:
- Virtualization Technology (VTx) = Disabled (recommended, Enable also worked)
- Virtualization Technology for Direct I/O (VTd) = Disabled (recommended, Enable also worked)
Built-In Device Options:
- Wake On LAN = Disabled
- Video memory size = 64 MB
- LAN/WLAN Auto Switching = Disabled
- Fingerprint Device = Disabled
Power Management Options:
- Extended Idle Power States = Disabled
- Deep sleep = You can keep this enabled
- Wake when Lid is Opened = Enabled
- Wake on USB = Disabled

**Comment by rahat14** [comment]
Thnx for all the direction sir,

**Comment by yahgoo** [comment]
Maybe u can try the recovery method from this video https://www.youtube.com/watch?v=JAnU-zF0yjE&t=143s

**Comment by rahat14** [comment]
yes , i am trying all the possible scenaario . https://www.hackintoshshop.com/3262/hackintosh-monterey-guide/ this site register is not working for me sir. can you share the download link

**Comment by yahgoo** [comment]
Try this uubyte https://www.uubyte.com/create-macos-bootable-usb-from-windows-10.html

**Comment by rahat14** [comment]
Here  is  the  video of error 
https://we.tl/t-GfLXncEKYV
Method Tried : Recovery method . EFI used was yours .
 the log file has this error - 
00:000 00:000 OCUI: Failed to load images for BsxDarkFenceOrangeRed1_
00:936 00:936 OC: External interface failure, fallback to builtin - Unsupported

**Comment by yahgoo** [comment]
u cannot start clean install Monterey with Windows dual boot.
I have no idea of the error log.
can u try install on another ssd or hdd? external ssd or hdd will do
